### ISSUE TITLE
lab02

### ISSUE THREAD

**Issue by MohammedAlMawlawi** [MohammedAlMawlawi/fall24#4]
### Learning Objectives

- Examine and test code to find injection vulnerabilities in applications.
- Write secure code to prevent vulnerabilities associated with command injection.

## Introduction
Injection vulnerabilities are a class of security weaknesses in software applications where an attacker can inject malicious input or code into an application's data or command stream. These vulnerabilities typically occur when an application fails to properly validate, sanitize, or handle untrusted input which can then be executed on a system and cause security issues.
Some of the common attacks that result from injection are:

- Command Injection
- Directory Traversal
- SQL Injection
- Cross-Site Scripting (XSS)
- LDAP Injection
- XPath Injection
- Header Injection

In this lab, you will learn about some injection vulnerabilities and how to mitigate them. 

##  Command Injection
Some applications may interact with the operating system and execute some external system commands. Command Injection vulnerabilities occur when untrusted data is used to construct system commands that are executed by the application. Attackers can execute arbitrary commands on the underlying system, potentially gaining unauthorized access or control.

##  Command Injection Example
In Java, one way to execute commands on the operating system is by calling the method Runtime.getRuntime().exec(command). Note that this method was deprecated very recently (2021).
The command parameter is a string representing the command to be executed.

- It can be a single string representing the entire command with its arguments, such as "sh -c ls -l /tmp" on Unix-like systems or "cmd.exe /c dir C:\\Users" on Windows. In this case, the command and its arguments are combined into a single string. Let's break it down:

1. "cmd.exe": This is the command that allows the app to run the Windows Command Prompt.
2. "/c": This is an argument passed to the Command Prompt. It stands for "carry out command" and then terminate.
3. "dir": This is the actual command that will be executed in the command prompt. In this example, it lists the contents of a directory on Windows. 
4. "C:\\Users" is the directory specified to list its content.

- However, the command string can be assembled by reading the directory name as user input and concatenating it with the first three parts of the command as you will see in the example code.

- [ ] On your VM, open a command prompt and try the dir command which lists the content of a directory to see its ouput:
dir "C:\Users"

- [ ] Try the echo command which prints out the given argument that follows it to the screen:

`echo "I have been hacked"`

- [ ] Create a new Java project.

- [ ] the starter file A02-StarterCode.zip, use the code in the file DirList.java.

- [ ] The app is supposed to receive the user's input for a directoryPath and list the content of that directory. Examine the code and note how the command is assembled by concatenation:

`String command = "cmd.exe /c dir \"" + directoryPath + "\"";
`
- [ ] Compile and run the app (CTRL+F5). Enter a directory name such as C:\Users. This will effectively execute the command on Windows as:

`dir "C:\Users"
`
- [ ] Test the program again with other directory names and watch the results. The output of the program should be the listing of files and subdirectories in the directory you specify in your input.

- [ ] Run the program again and enter the following input:

`C:\Users" & echo "The echo command was injected
`
- [ ] The & operator in the above payload tells the OS to execute a second command. Watch the result in this case and figure out why the double quotes were inserted in their specific locations.

- [ ] As mentioned above, the echo command is a non-destructive command, it just prints out the given string argument to the screen. However, an attacker may inject malicious commands such as:

- type filename (cat filename on Linux) which reads and prints the content of a file. This command violates the confidentiality of the system. Run the program again and enter as input:

`c:\Users" & type "./README.md
`
If you created your project correctly, you will see the content of the file README.md. This is an example of Directory Traversal vulnerability which is a type of Command Injection but utilizing the OS file system navigation API (./ current directory and ../ parent directory).

- del filename (rm filename on Linux) which deletes the specified file. This command violates the availability of the system. What about deleting all files on the computer, don't try this! You may destroy your virtual machine!

Note: When the same command injection attack is executed on a remote system (e.g., a web server), it's called Remote Code Execution.

## Injection Mitigation

1. The best mitigation technique against command injection is not to allow input from the user to be used along with system commands altogether. Most programs can perform the same functionality without using the input from the user. 

2. However, if the user's input is a must, whitelisting can be used to avoid allowing the user's input to be concatenated with the command and limits the user's ability to view only a subset of the system directories. In addition, we can avoid using the runtime method as it was deprecated for a reason (although late). For example, we can hardcode the directories that the user is allowed to view in an array and then ask the user to select the number of the directory that they need to list its content:

- [ ] Select one of the following directories to view its content:

- To list the content of C:/Users, type 1.
- To list the content of C:/Users/Admin, type 2.
- To list the content of C:/Users/Admin/Desktop, type 3.

Based on the selection made by the user, we can then map the integer input to one of the directories in the array and use the following code to view its content listing:

```
//Read user input 
String selectedDirectory = // and map it to a directory name from the array File dir = new File(selectedDirectory);
if (!dir.isDirectory()) {
    System.out.println("Not a directory");
} else {
    for (String file : dir.list()) {
        System.out.println(file);
    }
}
```

3. When the number of directories that the user can view is large, whitelisting becomes problematic. In this case, blacklisting can be used to avoid accepting input from the user that contains invalid characters for example. We will look at some examples of blacklisting in future labs.

## Task 1

- [ ] Make a second copy of the file DirLis.java and name it SecureDirList.java. 
- [ ] Remove the old code and write secure code that uses whitelisting. Decide what directories the user can view (at least five).
- [ ] Make sure to handle exceptions that may arise as a result of the user inputting invalid values such as strings or integers that are out of the array bounds.

## Task 2

- [ ] Create a lab report that contains your reflection on the important points that you learnt from doing this lab and any related search or discussion. Write your notes in a way that helps you remember when you study from them in the future, not only to get the lab grade. For example, you are expected to analyze the payload that was injected and realize how it exploits the vulnerability and try to come up with other payloads that may cause other security issues, just be careful when testing them.

## Submission
- [ ] Submit the report you created as a PDF file.
- [ ] Submit the java source code file for the secure directory lister. Do not zip the files.
